name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@01f39b179e76b7da3831bb70bef15e817df49590 # main
        with:
          repository: openstack/nova
          ref: 09c9826e1f2d802033f859cb0e89439632f885f8 # stable/zed

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@01f39b179e76b7da3831bb70bef15e817df49590 # main
        with:
          repository: vexxhost/nova-scheduler-filters
          ref: ceb2d182c0600134f97bcfef15caf0b05fe0477a # main

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@01f39b179e76b7da3831bb70bef15e817df49590 # main
        with:
          image-name: nova
          build-contexts: |
            nova=openstack/nova
            nova-scheduler-filters=vexxhost/nova-scheduler-filters
          push: ${{ github.event_name != 'pull_request' }}
