name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/nova
          ref: 121983b9450b1861b4e9b93a25c20349aa8ee084 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: vexxhost/nova-scheduler-filters
          ref: ceb2d182c0600134f97bcfef15caf0b05fe0477a # main

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          image-name: nova
          build-contexts: |
            nova=openstack/nova
            nova-scheduler-filters=vexxhost/nova-scheduler-filters
          push: ${{ github.event_name != 'pull_request' }}
