name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@main
        with:
          repository: openstack/nova
          ref: a4f1f2d3d6c112db2b5cce402435d273b2139479 # stable/2025.1

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@main
        with:
          repository: vexxhost/nova-scheduler-filters
          ref: ceb2d182c0600134f97bcfef15caf0b05fe0477a # main

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@main
        with:
          image-name: nova
          build-contexts: |
            nova=openstack/nova
            nova-scheduler-filters=vexxhost/nova-scheduler-filters
          push: ${{ github.event_name != 'pull_request' }}
